# Build Your Own Package

## Package Structure

Have a look at the repository of the Example package on GitHub to understand how a typical Julia package is structured.

👉 https://github.com/JuliaLang/Example.jl

Note the essential content of a package:
1. the `src` folder - containing `.jl` files with the implementation of your package
2. the `test` folder - containing `.jl` files with tests for the package's functionality
3. the `Project.toml` file - containing package information
4. the `README.md` - the starting point into the package's documentation

Furthermore note:
1. a `.gitignore` file - telling `git` to ignore some temporary files
2. a `LICENSE` - important for open source projects

## Package Implementation

In the following we are going to set up a new Julia Package step by step.

We are going to build a package with a collection of functions that generate special mathematical sequences - like the _Fibonacci sequence_ and the _Catalan numbers_.

<div style="border:2px solid gray; padding:10px;">

**ℹ Fibonacci Sequence**

The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, usually starting with 0 and 1. The $n$-th Fibonacci number $F_n$ is given by the formula:

$$ F_n = F_{n-1} + F_{n-2} $$

with initial conditions:

$$ F_0 = 0, \quad F_1 = 1 $$

This sequence appears in various aspects of mathematics, art, nature, and computer science.
</div>

Here is a possible implementation for the Fibonacci numbers:

In [1]:
function fibonacci_impl(n)
    fib_sequence = zeros(Int, n)
    fib_sequence[1] = 0
    fib_sequence[2] = 1
    for i = 3:n
        fib_sequence[i] = fib_sequence[i - 1] + fib_sequence[i - 2]
    end
    return fib_sequence
end

fibonacci_impl (generic function with 1 method)

In [2]:
fibonacci_impl(10)

10-element Vector{Int64}:
  0
  1
  1
  2
  3
  5
  8
 13
 21
 34

<div style="border:2px solid gray; padding:10px;">

**ℹ Catalan Numbers**

The Catalan numbers are a sequence of natural numbers important in combinatorial mathematics, with the $n$-th Catalan number given by the formula:

$$ C_n = \frac{(2n)!}{(n+1)!n!} $$

They count various combinatorial structures, such as the number of proper ways to parenthesize expressions and the number of binary trees with $n$ nodes.

</div>

📋 _Implement a function that generates the Catalan numbers for a given $n$_

In [3]:
# your code here


No implementation is complete without test code.

_📋 Verify the correctness of the implementation by writing a test suite._

In [4]:
# your test code here

## Setting Up the Package 

In [5]:
package_name = "Sequences"

"Sequences"

_📋Create a folder in a suitable location, name it like your package name. Inside, create a `src` folder._

A Julia package includes a `Project.toml` file with basic information about the package. A minimal file contains:

```
name = "$(package_name)"
uuid = "$(package_id)"
authors = $(authors)
version = "$(version)"
```

A package needs a unique identifier in the form of a UUID. This helps to identify the package in a decentralized ecosystem even if there are package naming clashes.

<div style="border:2px solid gray; padding:10px;">

A UUID (Universally Unique Identifier) is a 128-bit number used to uniquely identify information in computer systems, and a package requires one to ensure global uniqueness, preventing conflicts with packages of the same name across different systems and registries.

</div>

📋 _Use the `UUIDs` package to create a unique identifier for the new package_

In [6]:
# your code here

📋 _Create the `Project.toml` file for your new package and fill in the appropriate values_

Now it's time to place our functions in a module. Here is an example:

In [7]:
# Define the module name
module MyModuleName

# Import necessary modules. Example: Importing the Base module.
# using Base


# Define your functions, structs, constants, etc.
    """
        my_function(x)

    A simple function that returns the square of its argument.

    # Arguments
    - `x`: A number to be squared.

    # Examples
    ```julia
    my_function(4) # returns 16
    """
    function my_function(x)
        return x^2
    end

    # Export your functions, types, constants, etc., to make them public.
    export my_function

# You can include more functions, structs, and other definitions below.
end 

Main.MyModuleName

📋 _Create the source file `Sequences.jl` for the `Sequences` package and place it in the `src` folder._

## Importing the Package

In [8]:
using Pkg

Replace this with the path to your new package in order to test it:

In [9]:
path_to_package = "../../packages/Sequences"

"../../packages/Sequences"

In [10]:
Pkg.develop(path=path_to_package)

   Resolving package versions...


  No Changes to `~/Documents/Work/Training/point8/data-science-learning-paths/Project.toml`
  No Changes to `~/Documents/Work/Training/point8/data-science-learning-paths/Manifest.toml`


In [11]:
using Sequences

In [12]:
fibonacci(10)

10-element Vector{Int64}:
  0
  1
  1
  2
  3
  5
  8
 13
 21
 34

In [13]:
catalan(10)

10-element Vector{Rational{Int64}}:
    1//1
    1//1
    2//1
    5//1
   14//1
   42//1
  132//1
  429//1
 1430//1
 4862//1

---
_This notebook is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/). Copyright © 2018-2024 [Point 8 GmbH](https://point-8.de)_