# Numeric Computing in Julia

## Working with Arrays

Arrays are fundamental for numeric computing. Julia provides powerful built-in tools for creating and manipulating arrays.

### Creating Arrays

In [3]:
# Creating a vector (1D array)
vector = [1, 2, 3, 4, 5]


5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [4]:
# Creating a matrix (2D array)
matrix = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [5]:
# Creating a 3D array
array_3d = rand(4, 3, 2)  # random numbers

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.490551  0.696528  0.399422
 0.956578  0.413844  0.101444
 0.387868  0.371236  0.542478
 0.468687  0.933327  0.938082

[:, :, 2] =
 0.309949  0.4665    0.0365643
 0.399344  0.690447  0.18318
 0.969704  0.872456  0.307877
 0.189404  0.273142  0.926016

Construct an array by repeating the elements of an input array:

In [7]:
repeated_matrix = repeat(matrix, 2, 3)

6×9 Matrix{Int64}:
 1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6
 7  8  9  7  8  9  7  8  9
 1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6
 7  8  9  7  8  9  7  8  9

In this example:

- `matrix`: The input array that you want to repeat. 
- 2: the number of times each row of matrix will be repeated along the column dimension.
- 3: the number of times each column of matrix will be repeated along the row dimension. 

### Reshaping Arrays

The following function  rearranges the elements of the given array into a new array with the specified dimensions without changing the data. In the this example, a one-dimensional array vector is transformed into a 5-row, 1-column two-dimensional array (a column vector).

In [9]:
reshape(vector, (5, 1))

5×1 Matrix{Int64}:
 1
 2
 3
 4
 5

The next example takes a range of integers and reshapes it into a 3-row by 4-column matrix. The elements fill the matrix column-wise.

In [10]:
reshape(1:12, 3, 4)

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

### Accessing Arrays

Cou can access array elements and perform slicing. Here are some examples:

In [12]:
matrix

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [11]:
matrix[2, 3]  # Gets the element at row 2, column 3


6

In [13]:
matrix[1:2, 2:end]  # Gets a sub-matrix from rows 1 to 2 and columns 2 to the end

2×2 Matrix{Int64}:
 2  3
 5  6

In [14]:
matrix[1, :]  # Gets the first row

3-element Vector{Int64}:
 1
 2
 3

In [15]:
matrix[:, 3]  # Gets the third column

3-element Vector{Int64}:
 3
 6
 9

In [16]:
matrix[1:2:end, :]  # Gets rows with a step of 2 (e.g., 1st, 3rd, etc.)

2×3 Matrix{Int64}:
 1  2  3
 7  8  9

In [17]:
# Check if an element is in an array
ismember_single = 3 ∈ vector
println("Is 3 in the vector? ", ismember_single)

Is 3 in the vector? true


### Array Operations

In [19]:
# Element-wise addition
vector .+ 10

5-element Vector{Int64}:
 11
 12
 13
 14
 15

In [25]:
# Matrix multiplication
matrix * [0, 1, 0]

3-element Vector{Int64}:
 2
 5
 8

In [26]:
transpose(matrix)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

## Linear Algebra

Julia has built-in support for many linear algebraic operations.



In [27]:
using LinearAlgebra

Compute the eigenvalues and eigenvectors of a matrix:

In [29]:
eigen(matrix)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -1.1168439698070434
 -8.582743335036247e-16
 16.11684396980703
vectors:
3×3 Matrix{Float64}:
 -0.78583     0.408248  -0.231971
 -0.0867513  -0.816497  -0.525322
  0.612328    0.408248  -0.818673

Solve a linear system:

In [30]:
# Coefficient matrix
A = [3 2; 1 5]

# Constants vector
b = [18; 20]

# Solve the system A*x = b
x = A \ b

2-element Vector{Float64}:
 3.8461538461538463
 3.230769230769231

## Exercises

### Exercise Task 1

1. Create a 5x5 matrix X with elements from 1 to 25.
1. Extract the second and fourth rows of X into a new matrix Y.
1. Extract a 3x3 submatrix Z from the center of X.


In [ ]:
# your code here

### Exercise Task 2

1. Create two one-dimensional arrays D1 and D2, each with 5 elements.
1. Concatenate D1 and D2 into one array D3.
1. Split D3 back into two arrays of equal length.

In [ ]:
# your code here

### Exercise Task 3

1. Create a one-dimensional array original_array containing the first 24 positive integers.
1. Reshape this array into a 2D array (matrix) matrix_4x6 with 4 rows and 6 columns.
1. Transpose matrix_4x6 to create a new matrix matrix_6x4.
1. Reshape matrix_6x4 into a 3D array array_3D with dimensions 2x3x4.
1. Take the 3D array array_3D and reshape it back into a one-dimensional array flat_array ensuring that the elements are in the same order as original_array.
1. Create a function verify_reshape(original, reshaped) that checks if the reshaped array contains the same elements in the same order as the original array. It should return true if they match and false otherwise.

In [ ]:
# your code here

---
_This notebook is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/). Copyright © 2018-2024 [Point 8 GmbH](https://point-8.de)_^m